### ISSUE TITLE
getting 400 error

### ISSUE THREAD

**Issue by sumanindusnet** [CloudBoost/JavaScriptSDK#65]
I am using cloudboost SDK in angular2 project. When I am giving correct user credentials in login API  it is working fine, but if the credentials are wrong the request is getting 400 error with a error object, but it was supposed to be a 200 success status with the error object. I am using the API sample for login given in api documentation.

var user = new CB.CloudUser();
user.set('username', 'my_username');
user.set('password', 'my_solid_password');
user.logIn({
success: function(user) {
//Login successfull
},
error: function(err) {
//Error occured in user registration.
}
});

**Comment by nawazdhandala** [comment]
I think 400 code is correct. It means bad credentials.

**Comment by sumanindusnet** [comment]
but the err prams in the error section logging this in console instead of the error message. I have given an attachment of the same.
![untitled](https://cloud.githubusercontent.com/assets/13829449/25522939/73ec83bc-2c22-11e7-8038-c84c5c9fe2f8.png)


Error: Request failed with status code 400
    at createError (http://localhost:3000/vendor.bundle.js:78319:16) [angular]
    at settle (http://localhost:3000/vendor.bundle.js:78291:13) [angular]
    at XMLHttpRequest.handleLoad (http://localhost:3000/vendor.bundle.js:78179:8) [angular]
    at XMLHttpRequest.wrapFn [as __zone_symbol___onreadystatechange] (http://localhost:3000/polyfills.dll.js:4954:29) [angular]
    at Object.onInvokeTask (http://localhost:3000/vendor.dll.js:5592:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.dll.js:4152:36) [angular]
    at Zone.runTask (http://localhost:3000/polyfills.dll.js:3920:47) [<root> => angular]
    at XMLHttpRequest.ZoneTask.invoke (http://localhost:3000/polyfills.dll.js:4215:38) [<root>]
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (http://localhost:3000/vendor.bundle.js:71911:20)
    at Promise._resolveFromExecutor (http://localhost:3000/vendor.bundle.js:74052:11)
    at new Promise (http://localhost:3000/vendor.bundle.js:73651:15)
    at new Promise (http://localhost:3000/vendor.bundle.js:70630:28)
    at CloudBoost._CB2.default._request (http://localhost:3000/vendor.bundle.js:76800:16)
    at CloudUser._CB2.default.CloudUser.logIn (http://localhost:3000/vendor.bundle.js:91997:19)
    at http://localhost:3000/main.bundle.js:4374:18
    at new ZoneAwarePromise (http://localhost:3000/polyfills.dll.js:4531:29)
    at AuthService.webpackJsonpac__name_.91.AuthService.login (http://localhost:3000/main.bundle.js:4368:16)
    at Login.webpackJsonpac__name_.770.Login.onSubmit (http://localhost:3000/9.chunk.js:112:31)
    at Object.eval [as handleEvent] (ng:///LoginModule/Login.ngfactory.js:199:24)
    at handleEvent (http://localhost:3000/vendor.dll.js:13281:138)
    at callWithDebugContext (http://localhost:3000/vendor.dll.js:14489:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:3000/vendor.dll.js:14077:12)
    at dispatchEvent (http://localhost:3000/vendor.dll.js:10256:21)
    at http://localhost:3000/vendor.dll.js:12120:38
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:3000/vendor.dll.js:5316:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:3000/vendor.dll.js:459:16)
    at SafeSubscriber.next (http://localhost:3000/vendor.dll.js:408:22)
    at Subscriber._next (http://localhost:3000/vendor.dll.js:348:26)
    at Subscriber.next (http://localhost:3000/vendor.dll.js:312:18)
    at EventEmitter.Subject.next (http://localhost:3000/vendor.dll.js:673:25)
    at EventEmitter.emit (http://localhost:3000/vendor.dll.js:5290:76)
    at FormGroupDirective.onSubmit (http://localhost:3000/vendor.dll.js:34202:23)
    at Object.eval [as handleEvent] (ng:///LoginModule/Login.ngfactory.js:191:42)
    at handleEvent (http://localhost:3000/vendor.dll.js:13281:138)
    at callWithDebugContext (http://localhost:3000/vendor.dll.js:14489:42)
    at Object.debugHandleEvent [as handleEvent] (http://localhost:3000/vendor.dll.js:14077:12)
    at dispatchEvent (http://localhost:3000/vendor.dll.js:10256:21)
    at http://localhost:3000/vendor.dll.js:10846:38
    at HTMLFormElement.<anonymous> (http://localhost:3000/vendor.dll.js:18357:53)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.dll.js:4153:31)
    at Object.onInvokeTask (http://localhost:3000/vendor.dll.js:5592:37)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.dll.js:4152:36)
    at Zone.runTask (http://localhost:3000/polyfills.dll.js:3920:47)
    at HTMLFormElement.ZoneTask.invoke (http://localhost:3000/polyfills.dll.js:4215:38)

**Comment by nawazdhandala** [comment]
I think the response should be 401 
`
If the request included authentication credentials, then the 401 response indicates that authorization has been refused for those credentials. 
`
from https://httpstatuses.com/401
